### PR TITLE
1.0.1 rc1

### PR DESCRIPTION
**Pull request by 99sono**
Hi,

I would like you to consider the changes i've checked in to the 1.0.1 branch.
Please, I've tested it under welogic 12.1.2 and glassfish 3.1.2.9 both JEE 6 containers.

I would appreciate if you could review the branch and hopefully take it over.
The branches has:
(1) Synchronization that was missing on the resource manager - very simple synchroniztaiton
(2) Buts the Resource Manager as serilizable
(3) Reviews the process of generate unique ids - not even in the HEAD release is the code reselient to page refresh leaking images of 0 bytes due to the stream being closed.
(4) Is reselient to browser cache by producing a new unique id in a pseudo deterministic way, meaning that when it makes sense to produce a new unique id a new unique id is produced and it will be an id that the browser has not yet sean safeguarding from cache issues
(5) fixes leaking file input sream on the resource handler tha twas not closing the stream
(6) is more light weith in terms of pyhsical space consumption in the temp folder as it attempts on the fly to delete the stale old image generated on a previous request when a new stream content is created for the renderer

Kindest regards,
Nuno.

### CODE REVIEW

**Comment by 99sono** [comment]
There is something wrong with the pull request, as it says it is to be a pull request to the master.

It should have been targeting a the 1.0.0 branch actually.

**Comment by rdebusscher** [comment]
I don't have the time to review this for the moment, but I'll come back to it within a few weeks.

I will verify the changes against the Application on Tomcat where it was originally derived from.

Thx for the input
Rudy

**Comment by 99sono** [comment]
Hi No problem,

Until then, I will try to see if I find the time to merge my changes upwards to my local forked master branch, which should make it easier for you if you decide to merge it or only parts of it.

For the time being, I will be using the 1.0.1-RC1 as it works around the view access scoped limitation in a particular scenario of our application under primefaces 3.5 with delta spike.

Kindest regards.

**Comment by rdebusscher** [comment]
Your changes for issues #1, #2, #4, #6 and #7 are available in the branch **1.0.1**  

Still a SNAPSHOT version.

**Pull request closed without merging**
